const addon = require('./build/Release/node-opencv.node');

module.exports = {
    Mat: addon.Mat,
    imread: addon.Mat.imread,
    imdecode: addon.Mat.imdecode,
    imdecodeAsync: addon.Mat.imdecodeAsync,
    imreadAsync: addon.Mat.imreadAsync,
    TM_CCOEFF_NORMED: addon.TM_CCOEFF_NORMED,
    TM_CCORR_NORMED: addon.TM_CCORR_NORMED,
    TM_SQDIFF_NORMED: addon.TM_SQDIFF_NORMED,
    TM_CCOEFF: addon.TM_CCOEFF,
    TM_CCORR: addon.TM_CCORR,
    TM_SQDIFF: addon.TM_SQDIFF,
    IMREAD_COLOR: addon.IMREAD_COLOR,
    IMREAD_GRAYSCALE: addon.IMREAD_GRAYSCALE,
    IMREAD_UNCHANGED: addon.IMREAD_UNCHANGED,
    IMREAD_ANYDEPTH: addon.IMREAD_ANYDEPTH,
    IMREAD_ANYCOLOR: addon.IMREAD_ANYCOLOR,
    CV_8S: addon.CV_8S,
    CV_8U: addon.CV_8U,
    CV_8UC1: addon.CV_8UC1,
    CV_8UC3: addon.CV_8UC3,
    CV_8UC4: addon.CV_8UC4,
    CV_16S: addon.CV_16S,
    CV_32S: addon.CV_32S,
    COLOR_GRAY2RGBA: addon.COLOR_GRAY2RGBA,
    COLOR_RGB2RGBA: addon.COLOR_RGB2RGBA,
};
